// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds(
	id,
	title,
	description,
	url,
	created_at,
	updated_at
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP
) 
RETURNING id, title, description, url, last_fetched_at, created_at, updated_at
`

type CreateFeedParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Url         string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Url,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fetchFeedByUrl = `-- name: FetchFeedByUrl :one
SELECT
	id,
	title,
	description,
	url,
	last_fetched_at
FROM feeds
WHERE url = $1
LIMIT 1
`

type FetchFeedByUrlRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Url           string
	LastFetchedAt sql.NullTime
}

func (q *Queries) FetchFeedByUrl(ctx context.Context, url string) (FetchFeedByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, fetchFeedByUrl, url)
	var i FetchFeedByUrlRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}

const fetchFeeds = `-- name: FetchFeeds :many
SELECT 
	id,
	title,
	description,
	url,
	last_fetched_at
FROM feeds
ORDER BY last_fetched_at DESC
`

type FetchFeedsRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Url           string
	LastFetchedAt sql.NullTime
}

func (q *Queries) FetchFeeds(ctx context.Context) ([]FetchFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchFeedsRow
	for rows.Next() {
		var i FetchFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctFeeds = `-- name: GetDistinctFeeds :many
SELECT DISTINCT
	id,
	title,
	description,
	url,
	last_fetched_at
FROM feeds
ORDER BY title DESC
`

type GetDistinctFeedsRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Url           string
	LastFetchedAt sql.NullTime
}

func (q *Queries) GetDistinctFeeds(ctx context.Context) ([]GetDistinctFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctFeedsRow
	for rows.Next() {
		var i GetDistinctFeedsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFeeds = `-- name: GetUserFeeds :many
SELECT
	f.title,
	f.description,
	f.url
FROM feeds_users fu

LEFT JOIN feeds f
	ON fu.feed_id = f.id
LEFT JOIN users u
	ON fu.user_id = u.id

WHERE u.id = $1
`

type GetUserFeedsRow struct {
	Title       sql.NullString
	Description sql.NullString
	Url         sql.NullString
}

func (q *Queries) GetUserFeeds(ctx context.Context, id uuid.UUID) ([]GetUserFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedsRow
	for rows.Next() {
		var i GetUserFeedsRow
		if err := rows.Scan(&i.Title, &i.Description, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds SET last_fetched_at = $1 WHERE id = $2 RETURNING id, title, description, url, last_fetched_at, created_at, updated_at
`

type UpdateFeedParams struct {
	LastFetchedAt sql.NullTime
	ID            uuid.UUID
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed, arg.LastFetchedAt, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
