// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addFeedForUser = `-- name: AddFeedForUser :one
WITH inserted AS (
	INSERT INTO feeds_users(
		id,
		feed_id,
		user_id,
		created_at,
		updated_at
	) VALUES ($1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	RETURNING id, user_id, feed_id, created_at, updated_at
)
SELECT inserted.feed_id, inserted.user_id, f.title, f.url, f.description
FROM inserted
JOIN feeds AS f ON f.id = inserted.feed_id
`

type AddFeedForUserParams struct {
	ID     uuid.UUID
	FeedID uuid.UUID
	UserID uuid.UUID
}

type AddFeedForUserRow struct {
	FeedID      uuid.UUID
	UserID      uuid.UUID
	Title       string
	Url         string
	Description sql.NullString
}

func (q *Queries) AddFeedForUser(ctx context.Context, arg AddFeedForUserParams) (AddFeedForUserRow, error) {
	row := q.db.QueryRowContext(ctx, addFeedForUser, arg.ID, arg.FeedID, arg.UserID)
	var i AddFeedForUserRow
	err := row.Scan(
		&i.FeedID,
		&i.UserID,
		&i.Title,
		&i.Url,
		&i.Description,
	)
	return i, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds(
	id,
	title,
	description,
	url,
	created_at,
	updated_at
)
VALUES (
	$1,
	$2,
	$3,
	$4,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP
) 
RETURNING id, title, description, url, last_fetched_at, created_at, updated_at
`

type CreateFeedParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Url         string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Url,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :one
DELETE FROM feeds WHERE id = $1
RETURNING id, title, description, url, last_fetched_at, created_at, updated_at
`

func (q *Queries) DeleteFeed(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, deleteFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFeedForUser = `-- name: DeleteFeedForUser :one
WITH deleted AS (
    DELETE FROM feeds_users
    WHERE user_id = $1 AND feed_id=$2
    RETURNING feed_id, user_id
)
SELECT deleted.feed_id, deleted.user_id, f.title, f.url, f.description
FROM deleted
JOIN feeds AS f ON f.id = deleted.feed_id
`

type DeleteFeedForUserParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

type DeleteFeedForUserRow struct {
	FeedID      uuid.UUID
	UserID      uuid.UUID
	Title       string
	Url         string
	Description sql.NullString
}

func (q *Queries) DeleteFeedForUser(ctx context.Context, arg DeleteFeedForUserParams) (DeleteFeedForUserRow, error) {
	row := q.db.QueryRowContext(ctx, deleteFeedForUser, arg.UserID, arg.FeedID)
	var i DeleteFeedForUserRow
	err := row.Scan(
		&i.FeedID,
		&i.UserID,
		&i.Title,
		&i.Url,
		&i.Description,
	)
	return i, err
}

const fetchFeeds = `-- name: FetchFeeds :many
SELECT 
	feeds.id, feeds.title, feeds.description, feeds.url, feeds.last_fetched_at, feeds.created_at, feeds.updated_at
FROM feeds
ORDER BY last_fetched_at DESC
`

type FetchFeedsRow struct {
	Feed Feed
}

func (q *Queries) FetchFeeds(ctx context.Context) ([]FetchFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchFeedsRow
	for rows.Next() {
		var i FetchFeedsRow
		if err := rows.Scan(
			&i.Feed.ID,
			&i.Feed.Title,
			&i.Feed.Description,
			&i.Feed.Url,
			&i.Feed.LastFetchedAt,
			&i.Feed.CreatedAt,
			&i.Feed.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctFeeds = `-- name: GetDistinctFeeds :many
SELECT DISTINCT
	feeds.id, feeds.title, feeds.description, feeds.url, feeds.last_fetched_at, feeds.created_at, feeds.updated_at
FROM feeds
ORDER BY title DESC
`

type GetDistinctFeedsRow struct {
	Feed Feed
}

func (q *Queries) GetDistinctFeeds(ctx context.Context) ([]GetDistinctFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctFeedsRow
	for rows.Next() {
		var i GetDistinctFeedsRow
		if err := rows.Scan(
			&i.Feed.ID,
			&i.Feed.Title,
			&i.Feed.Description,
			&i.Feed.Url,
			&i.Feed.LastFetchedAt,
			&i.Feed.CreatedAt,
			&i.Feed.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctFeedsForUser = `-- name: GetDistinctFeedsForUser :many
SELECT DISTINCT
	feeds.id, feeds.title, feeds.description, feeds.url, feeds.last_fetched_at, feeds.created_at, feeds.updated_at,
	fu.user_id
FROM feeds
LEFT JOIN feeds_users fu
ON fu.feed_id = feeds.id AND fu.user_id = $1

WHERE fu.user_id = $1
ORDER BY feeds.title ASC
`

type GetDistinctFeedsForUserRow struct {
	Feed   Feed
	UserID uuid.NullUUID
}

func (q *Queries) GetDistinctFeedsForUser(ctx context.Context, userID uuid.UUID) ([]GetDistinctFeedsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctFeedsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctFeedsForUserRow
	for rows.Next() {
		var i GetDistinctFeedsForUserRow
		if err := rows.Scan(
			&i.Feed.ID,
			&i.Feed.Title,
			&i.Feed.Description,
			&i.Feed.Url,
			&i.Feed.LastFetchedAt,
			&i.Feed.CreatedAt,
			&i.Feed.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT
	feeds.id, feeds.title, feeds.description, feeds.url, feeds.last_fetched_at, feeds.created_at, feeds.updated_at
FROM feeds
WHERE id = $1
LIMIT 1
`

type GetFeedByIDRow struct {
	Feed Feed
}

func (q *Queries) GetFeedByID(ctx context.Context, id uuid.UUID) (GetFeedByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i GetFeedByIDRow
	err := row.Scan(
		&i.Feed.ID,
		&i.Feed.Title,
		&i.Feed.Description,
		&i.Feed.Url,
		&i.Feed.LastFetchedAt,
		&i.Feed.CreatedAt,
		&i.Feed.UpdatedAt,
	)
	return i, err
}

const getFeedByUrl = `-- name: GetFeedByUrl :one
SELECT
	feeds.id, feeds.title, feeds.description, feeds.url, feeds.last_fetched_at, feeds.created_at, feeds.updated_at
FROM feeds
WHERE url = $1
LIMIT 1
`

type GetFeedByUrlRow struct {
	Feed Feed
}

func (q *Queries) GetFeedByUrl(ctx context.Context, url string) (GetFeedByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, getFeedByUrl, url)
	var i GetFeedByUrlRow
	err := row.Scan(
		&i.Feed.ID,
		&i.Feed.Title,
		&i.Feed.Description,
		&i.Feed.Url,
		&i.Feed.LastFetchedAt,
		&i.Feed.CreatedAt,
		&i.Feed.UpdatedAt,
	)
	return i, err
}

const getUserFeeds = `-- name: GetUserFeeds :many
SELECT
	
FROM feeds_users fu

LEFT JOIN feeds f
	ON fu.feed_id = f.id
LEFT JOIN users u
	ON fu.user_id = u.id

WHERE u.id = $1
AND f.id < COALESCE($2, 'ffffffff-ffff-ffff-ffff-ffffffffffff')
ORDER BY f.id DESC
LIMIT 51
`

type GetUserFeedsParams struct {
	ID     uuid.UUID
	Cursor uuid.NullUUID
}

type GetUserFeedsRow struct {
	Feed Feed
}

func (q *Queries) GetUserFeeds(ctx context.Context, arg GetUserFeedsParams) ([]GetUserFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFeeds, arg.ID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFeedsRow
	for rows.Next() {
		var i GetUserFeedsRow
		if err := rows.Scan(
			&i.Feed.ID,
			&i.Feed.Title,
			&i.Feed.Description,
			&i.Feed.Url,
			&i.Feed.LastFetchedAt,
			&i.Feed.CreatedAt,
			&i.Feed.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds SET last_fetched_at = $1 WHERE id = $2 RETURNING id, title, description, url, last_fetched_at, created_at, updated_at
`

type UpdateFeedParams struct {
	LastFetchedAt sql.NullTime
	ID            uuid.UUID
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, updateFeed, arg.LastFetchedAt, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
