// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
	id, created_at,	updated_at, title, url, description, published_at, feed_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, feed_id, title, url, description, published_at, created_at, updated_at
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT
	p.id,
	p.title,
	p.url,
	p.description,
	f.title as FeedTitle,
	f.url as FeedURL,
	pu.is_read,
	p.published_at
FROM posts as p

LEFT JOIN feeds_users fu
ON p.feed_id = fu.feed_id AND fu.user_id = $1

LEFT JOIN posts_users pu
ON p.id = pu.post_id AND pu.user_id = $1

LEFT JOIN feeds f
ON f.id = fu.feed_id

WHERE p.id = $2
`

type GetPostByIDParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

type GetPostByIDRow struct {
	ID          uuid.UUID
	Title       string
	Url         string
	Description sql.NullString
	Feedtitle   sql.NullString
	Feedurl     sql.NullString
	IsRead      sql.NullBool
	PublishedAt time.Time
}

func (q *Queries) GetPostByID(ctx context.Context, arg GetPostByIDParams) (GetPostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, arg.UserID, arg.ID)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.Feedtitle,
		&i.Feedurl,
		&i.IsRead,
		&i.PublishedAt,
	)
	return i, err
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT
	p.id,
	p.title,
	p.url,
	p.description,
	f.title as FeedTitle,
	f.url as FeedUrl,
	pu.is_read,
	p.published_at
FROM posts as p

LEFT JOIN feeds_users fu
ON p.feed_id = fu.feed_id AND fu.user_id = $1

LEFT JOIN posts_users pu
ON p.id = pu.post_id AND pu.user_id = $1

LEFT JOIN feeds f
ON fu.feed_id = f.id

WHERE fu.user_id = $2
AND (
    (published_at < COALESCE($3, '9999-12-31'::TIMESTAMP))
    OR (
        published_at = COALESCE($3, '9999-12-31'::TIMESTAMP)
        AND p.id < COALESCE($4, CAST('ffffffff-ffff-ffff-ffff-ffffffffffff' AS UUID))
    )
)
ORDER BY published_at DESC, p.id DESC
LIMIT 51
`

type GetPostsForUserParams struct {
	UserID     uuid.UUID
	CursorDate sql.NullTime
	CursorID   uuid.NullUUID
}

type GetPostsForUserRow struct {
	ID          uuid.UUID
	Title       string
	Url         string
	Description sql.NullString
	Feedtitle   sql.NullString
	Feedurl     sql.NullString
	IsRead      sql.NullBool
	PublishedAt time.Time
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser,
		arg.UserID,
		arg.UserID,
		arg.CursorDate,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.Feedtitle,
			&i.Feedurl,
			&i.IsRead,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostAsRead = `-- name: MarkPostAsRead :one
INSERT INTO posts_users(
	id,
	post_id,
	user_id,
	is_read,
	created_at,
	updated_at
)
VALUES ($1, $2, $3, $4, $5, $6)

ON CONFLICT (post_id, user_id) DO UPDATE SET
	is_read = EXCLUDED.is_read,
	updated_at = EXCLUDED.updated_at
RETURNING id, post_id, user_id, is_read, created_at, updated_at
`

type MarkPostAsReadParams struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.UUID
	IsRead    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) MarkPostAsRead(ctx context.Context, arg MarkPostAsReadParams) (PostsUser, error) {
	row := q.db.QueryRowContext(ctx, markPostAsRead,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.IsRead,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PostsUser
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const togglePostReadStatus = `-- name: TogglePostReadStatus :one
INSERT INTO posts_users(
	id,
	post_id,
	user_id,
	is_read,
	created_at,
	updated_at
)
VALUES ($1, $2, $3, $4, $5, $6)

ON CONFLICT (post_id, user_id) DO UPDATE SET
	is_read = NOT posts_users.is_read,
	updated_at = EXCLUDED.updated_at
RETURNING id, post_id, user_id, is_read, created_at, updated_at
`

type TogglePostReadStatusParams struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.UUID
	IsRead    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) TogglePostReadStatus(ctx context.Context, arg TogglePostReadStatusParams) (PostsUser, error) {
	row := q.db.QueryRowContext(ctx, togglePostReadStatus,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.IsRead,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PostsUser
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
