CREATE TABLE IF NOT EXISTS feeds (
	id UUID PRIMARY KEY,
	title TEXT NOT NULL,
	description TEXT,
	url TEXT NOT NULL UNIQUE,
	last_fetched_at TIMESTAMP DEFAULT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL
);
