CREATE TABLE IF NOT EXISTS posts (
	id UUID PRIMARY KEY,
	feed_id UUID NOT NULL,
	title TEXT NOT NULL,
	url TEXT NOT NULL UNIQUE,
	description TEXT,
	published_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,

	FOREIGN KEY (feed_id) REFERENCES feeds(id)
	ON DELETE CASCADE
);
